Features/products
saintajax/team-project pull request #2
Opened 2022-08-26 15:36 UTC by ShcherbatayaLuna

Add section products

2022-08-27 17:20 UTC, saintajax requested changes
- h2 и  p  в шапке секции  - убрать лишние марджины (останется один между  p  и h2);
- поменять местами after и beforre;
- в десктопной версии текст над заголовком по макету 30 шрифтом у тебя 18;
- по макету заголовок в декстопной версии  имеет letter spacing 6%;
- в планшетной версии текст над заголовком по макету 22 шрифтом у тебя 18;
- в карточка у текста обнулить верхний и нижний марджин.

2022-08-27 17:22 UTC, saintajax commented
Также замени фон с jpg на svg. Будет значительно меньше css.

2022-08-27 22:23 UTC, ShcherbatayaLuna commented
> Также замени фон с jpg на svg. Будет значительно меньше css.

2022-08-27 22:30 UTC, ShcherbatayaLuna commented
> * h2 и  p  в шапке секции  - убрать лишние марджины (останется один между  p  и h2);
> * поменять местами after и beforre;
> * в десктопной версии текст над заголовком по макету 30 шрифтом у тебя 18;
> * по макету заголовок в декстопной версии  имеет letter spacing 6%;
> * в планшетной версии текст над заголовком по макету 22 шрифтом у тебя 18;
> * в карточка у текста обнулить верхний и нижний марджин.

Я все это переделела.
Только текст в карточках по обьему выглядит не так как на макете.

2022-08-27 22:30 UTC, ShcherbatayaLuna commented
> Также замени фон с jpg на svg. Будет значительно меньше css.

Готово

2022-08-28 09:38 UTC, saintajax commented
Текст над заголовком в планшетной версии должен быть 22 шрифтом у тебя 18.
Сломалось позиционирование картинок.

2022-08-28 09:38 UTC, saintajax requested changes
Текст над заголовком в планшетной версии должен быть 22 шрифтом у тебя 18.
Сломалось позиционирование картинок.

2022-08-28 15:32 UTC, saintajax commented
В мобильной версии, когда сжимаешь до 320 px картинки товаров уезжают!

2022-08-29 08:16 UTC, saintajax approved these changes

2022-08-29 08:16 UTC, merged